#!/bin/sh -x

MOZIOT_HOME=${1:-/usr/share/things-gateway}

run_app() {

    cd ${MOZIOT_HOME}

    echo "node version"
    node --version

    echo "npm version"
    npm --version

    echo "Starting gateway ..."
    npm start

}

run_app
