#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service()
{
	procd_open_instance
	procd_set_param env HOME=/root NODE_PATH=/usr/lib/node/zwave-js/node_modules:/usr/lib/node/zwave-js/node_modules/winston/node_modules/ STORE_DIR=/root/.zwave-js-ui ZWAVEJS_EXTERNAL_CONFIG=/root/.zwave-js-ui/.config-db HOST=0.0.0.0
	procd_set_param command /usr/bin/zwave-js-ui
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
